name: Release

on:
  push:
    branches: ["*"]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get Changed Packages
        id: get-changed-packages
        run: |
          curl -O https://coralogix-public.s3-eu-west-1.amazonaws.com/cxctl/latest/cxctl-Linux.gz
          echo 1
          gunzip -N cxctl-*.gz
          echo 2
          chmod +x cxctl
          echo 3
          timeout 5s ./cxctl livetail --region "eu" --api-key "44f916b5-51a8-4427-b21d-85b5d2da82fc" --format pretty --application "app" --subsystem "sub"
          echo 4
